name: Build Ubuntu Artifact

on:
  push:
    branches:
      - is-not-zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build executable
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: "0"
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-ubuntu-amd64
          path: bin/gh
