name: Build Termux Artifact

on:
  push:
    branches:
      - is-not-zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build executable
        run: |
          export CC=$(ls $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android*-clang | sort | tail -n 1)
          export GOOS=android
          export GOARCH=arm64
          export CGO_ENABLED=1
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-termux-arm64
          path: bin/gh
